# Generated by Django 6.0.2 on 2026-02-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_customer_name_order_phone_order_shipping_address_and_more'),
        ('products', '0003_category_products_ca_section_5dc8a0_idx_and_more'),
        ('users', '0003_alter_customer_phone'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['recipient_type', 'created_at'], name='orders_bill_recipie_171456_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['phone', 'created_at'], name='orders_bill_phone_a95875_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['phone', 'created_at'], name='orders_orde_phone_ba307f_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status', 'created_at'], name='orders_orde_status_25e057_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'product'], name='orders_orde_order_i_52f79a_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['product'], name='orders_orde_product_32ff41_idx'),
        ),
    ]
