# Generated by Django 6.0.2 on 2026-02-14 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_bill_orders_bill_recipie_171456_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=120)),
                ('product_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales_records', to='orders.order')),
            ],
            options={
                'indexes': [models.Index(fields=['sold_at'], name='orders_sale_sold_at_a4381d_idx'), models.Index(fields=['category', 'sold_at'], name='orders_sale_categor_376c15_idx'), models.Index(fields=['product_name', 'sold_at'], name='orders_sale_product_df4d92_idx')],
            },
        ),
    ]
