# Generated by Django 6.0.2 on 2026-02-24 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_salesrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceablePincode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6, unique=True)),
                ('area_name', models.CharField(blank=True, default='', max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='orders_serv_code_8c9f95_idx'), models.Index(fields=['is_active', 'code'], name='orders_serv_is_acti_50b61c_idx')],
            },
        ),
    ]
