# Generated by Django 6.0.2 on 2026-02-23 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        ('orders', '0005_salesrecord'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='notification',
            name='event_type',
            field=models.CharField(choices=[('ORDER_PLACED', 'Order Placed'), ('ORDER_CONFIRMED', 'Order Confirmed')], default='ORDER_PLACED', max_length=32),
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_identifier',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='recipient_type',
            field=models.CharField(choices=[('USER', 'User'), ('ADMIN', 'Admin')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient_type', 'recipient_identifier', 'is_read', 'created_at'], name='notificatio_recipie_4249bc_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['order', 'event_type', 'recipient_type'], name='notificatio_order_i_478dbf_idx'),
        ),
    ]
