# Generated by Django 6.0.2 on 2026-02-14 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_category_options_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['section', 'name'], name='products_ca_section_5dc8a0_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'name'], name='products_pr_categor_cd4531_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'is_available'], name='products_pr_categor_c898cc_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['is_available', 'created_at'], name='products_pr_is_avai_de086a_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name'], name='products_pr_name_9ff0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='productviewlog',
            index=models.Index(fields=['product', 'viewed_at'], name='products_pr_product_bf1f64_idx'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name'], name='products_se_name_6a2191_idx'),
        ),
    ]
