# Generated by Django 6.0.2 on 2026-02-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category_products_ca_section_5dc8a0_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock_qty',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
