# Generated by Django 6.0.2 on 2026-02-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_stock_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=220)),
                ('image', models.ImageField(upload_to='ads/')),
                ('cta_label', models.CharField(blank=True, default='', max_length=40)),
                ('cta_url', models.CharField(blank=True, default='', max_length=500)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'display_order'], name='products_ad_is_acti_a18146_idx')],
            },
        ),
    ]
